name: cata2data-env
channels:
- defaults
dependencies:
- python>=3.9
- numpy=1.23
- anaconda
- pip
- pip:
  - astropy==5.2.1
  - matplotlib==3.6.3
  - pandas==1.5.3
  - spectral-cube==0.6.0
  - regions==0.7
